### ISSUE TITLE
Fix a variable that is not being correctly filled in by Sass.

### ISSUE THREAD

**Issue by louh** [mapzen/styleguide#467]
In our generated CSS, there is a Sass variable that is not being filled in. See for example, https://mapzen.com/common/styleguide/styles/blog.css, line 6685:

```css
.overflowing, .overflowing-left, .overflowing-right {
  margin-left: -180px;
  margin-right: -120px;
  max-width: calc(100% + $overflow-extra-width);
  position: relative; }
  @media (min-width: 768px) {
    .overflowing, .overflowing-left, .overflowing-right {
      height: 406px; } }
```

Notice that `$overflow-extra-width` exists here as a variable in the compiled CSS.

Possibly needs to be addressed in: https://github.com/mapzen/styleguide/blob/master/src/stylesheets/project_specific/blog/_index-overflowing-section.scss

CSS errors cause the minifier to break, so this is blocking #466.
